=== toivotuo/tapestry/tapestry/router/xsd/rocs.001.001.06.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="urn:rocs.001.001.06"
    targetNamespace="urn:rocs.001.001.06"
    elementFormDefault="qualified">
  <xs:element name="Document" type="Document"/>
  <xs:simpleType name="AnyBICIdentifier">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]{6,6}[A-Z2-9][A-NP-Z0-9]([A-Z0-9]{3,3}){0,1}"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="AOSList">
    <xs:sequence>
      <xs:element name="AOSId" type="xs:decimal" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="CountryCode">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]{2,2}"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="CSMIdentifier">
    <xs:sequence>
      <xs:element name="PtyId" type="PartyIdentification1Choice"/>
      <xs:element name="PreferredIndicator" type="xs:boolean"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CurrencyAndAmount">
    <xs:simpleContent>
      <xs:extension base="CurrencyAndAmount_SimpleType">
        <xs:attribute name="Ccy" type="CurrencyCode" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:simpleType name="CurrencyAndAmount_SimpleType">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="0"/>
      <xs:totalDigits value="18"/>
      <xs:fractionDigits value="5"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="CurrencyCode">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]{3,3}"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="CutOffType">
    <xs:sequence>
      <xs:element name="Time" type="ISOTime"/>
      <xs:element name="RelDays" type="xs:nonNegativeInteger"/>
      <xs:element name="TimeZone" type="Max16Text"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="DateTimePeriod">
    <xs:sequence>
      <xs:element name="FrDtTm" type="ISODateTime"/>
      <xs:element name="ToDtTm" type="ISODateTime" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Document">
    <xs:sequence>
      <xs:element name="rocs.001.001.06" type="rocs.001.001.06"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="FinancialInstitutionIdentification">
    <xs:sequence>
      <xs:element name="BIC" type="AnyBICIdentifier"/>
      <xs:element name="NmAndAdr" type="LongNameAndAddress2"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="GenericIdentification1">
    <xs:sequence>
      <xs:element name="Id" type="Max35Text"/>
      <xs:element name="SchmeNm" type="Max35Text" minOccurs="0"/>
      <xs:element name="Issr" type="Max35Text" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="GroupHeader">
    <xs:sequence>
      <xs:element name="MsgId" type="Max35Text"/>
      <xs:element name="CreDtTm" type="ISODateTime"/>
      <xs:element name="PtyId" type="PartyIdentification1Choice"/>
      <xs:element name="FullTable" type="xs:boolean"/>
      <xs:element name="FileValidityDate" type="ISODateTime"/>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="ISODateTime">
    <xs:restriction base="xs:dateTime"/>
  </xs:simpleType>
  <xs:simpleType name="ISOTime">
    <xs:restriction base="xs:time"/>
  </xs:simpleType>
  <xs:complexType name="LongNameAndAddress2">
    <xs:sequence>
      <xs:element name="Nm" type="Max140Text"/>
      <xs:element name="Adr" type="LongPostalAddress1Choice" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="LongPostalAddress1Choice">
    <xs:sequence>
      <xs:choice>
        <xs:element name="Ustrd" type="Max140Text"/>
        <xs:element name="Strd" type="StructuredLongPostalAddress1"/>
      </xs:choice>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="Max140Text">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="140"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Max16Text">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="16"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Max35Text">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="35"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="NameAndAddress2">
    <xs:sequence>
      <xs:element name="Nm" type="Max35Text"/>
      <xs:element name="Adr" type="LongPostalAddress1Choice" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PartyIdentification1Choice">
    <xs:sequence>
      <xs:choice>
        <xs:element name="BICOrBEI" type="AnyBICIdentifier"/>
        <xs:element name="PrtryId" type="GenericIdentification1"/>
        <xs:element name="NmAndAdr" type="NameAndAddress2"/>
      </xs:choice>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PriceIndication">
    <xs:choice>
      <xs:element name="Amount" type="CurrencyAndAmount"/>
      <xs:element name="Indication" type="Max35Text"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="ProductIdentifier">
    <xs:sequence>
      <xs:element name="ProductName" type="Max16Text"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ReachEntry">
    <xs:sequence>
      <xs:element name="Status" type="Max16Text"/>
      <xs:element name="Validity" type="DateTimePeriod"/>
      <xs:element name="Participant" type="FinancialInstitutionIdentification"/>
      <xs:element name="Product" type="ProductIdentifier"/>
      <xs:element name="CSM" type="CSMIdentifier" minOccurs="0"/>
      <xs:element name="CutOff" type="CutOffType"/>
      <xs:element name="SettlmConfirm" type="SettlementConfirmation" minOccurs="0"/>
      <xs:element name="SupportedAOS" type="AOSList" minOccurs="0"/>
      <xs:element name="PriceIndicator" type="PriceIndication" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="rocs.001.001.06">
    <xs:sequence>
      <xs:element name="GrpHdr" type="GroupHeader"/>
      <xs:element name="RchEntry" type="ReachEntry" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="SettlementConfirmation">
    <xs:sequence>
      <xs:element name="GuaranteedTime" type="ISOTime"/>
      <xs:element name="DaysDelay" type="xs:nonNegativeInteger"/>
      <xs:element name="TimeZone" type="Max16Text"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="StructuredLongPostalAddress1">
    <xs:sequence>
      <xs:element name="BldgNm" type="Max35Text" minOccurs="0"/>
      <xs:element name="StrtNm" type="Max35Text" minOccurs="0"/>
      <xs:element name="StrtBldgId" type="Max35Text" minOccurs="0"/>
      <xs:element name="Flr" type="Max16Text" minOccurs="0"/>
      <xs:element name="TwnNm" type="Max35Text"/>
      <xs:element name="DstrctNm" type="Max35Text" minOccurs="0"/>
      <xs:element name="RgnId" type="Max35Text" minOccurs="0"/>
      <xs:element name="Stat" type="Max35Text" minOccurs="0"/>
      <xs:element name="CtyId" type="Max35Text" minOccurs="0"/>
      <xs:element name="Ctry" type="CountryCode"/>
      <xs:element name="PstCdId" type="Max16Text"/>
      <xs:element name="POB" type="Max16Text" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== toivotuo/tapestry/tapestry/router/fixtures/2018081300001FMARKDEFF.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2012 rel. 2 sp1 (http://www.altova.com) by 21 users of IT (Deutsche Bundesbank Frankfurt) -->
<!--Achtung: Beispieldatei, keine Produktivdaten! -->
<!--Beispieldatei SCL-Teilnehmer, Full table -->
<Document xsi:schemaLocation="urn:rocs.001.001.06 Rocs.001.001.06.xsd" xmlns="urn:rocs.001.001.06" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<rocs.001.001.06>
		<GrpHdr>
			<MsgId>MARKDEFF201808090001</MsgId>
			<CreDtTm>2018-08-09T00:00:00</CreDtTm>
			<PtyId>
				<BICOrBEI>MARKDEFFXXX</BICOrBEI>
			</PtyId>
			<FullTable>1</FullTable>
			<FileValidityDate>2018-08-13T00:00:00</FileValidityDate>
		</GrpHdr>
		<RchEntry>
			<Status>existing</Status>
			<Validity>
				<FrDtTm>2013-10-07T15:00:00</FrDtTm>
			</Validity>
			<Participant>
				<BIC>AAAADEFF</BIC>
				<NmAndAdr>
					<Nm>A-Bank</Nm>
				</NmAndAdr>
			</Participant>
			<Product>
				<ProductName>SCT</ProductName>
			</Product>
			<CSM>
				<PtyId>
					<BICOrBEI>MARKDEFF</BICOrBEI>
				</PtyId>
				<PreferredIndicator>1</PreferredIndicator>
			</CSM>
			<CutOff>
				<Time>15:00:00</Time>
				<RelDays>0</RelDays>
				<TimeZone>CET</TimeZone>
			</CutOff>
		</RchEntry>
		<RchEntry>
			<Status>existing</Status>
			<Validity>
				<FrDtTm>2013-09-09T15:00:00</FrDtTm>
			</Validity>
			<Participant>
				<BIC>AAAADEFF</BIC>
				<NmAndAdr>
					<Nm>A-Bank</Nm>
				</NmAndAdr>
			</Participant>
			<Product>
				<ProductName>SDD core</ProductName>
			</Product>
			<CSM>
				<PtyId>
					<BICOrBEI>MARKDEFF</BICOrBEI>
				</PtyId>
				<PreferredIndicator>1</PreferredIndicator>
			</CSM>
			<CutOff>
				<Time>15:00:00</Time>
				<RelDays>0</RelDays>
				<TimeZone>CET</TimeZone>
			</CutOff>
		</RchEntry>
		<RchEntry>
			<Status>existing</Status>
			<Validity>
				<FrDtTm>2013-09-09T14:00:00</FrDtTm>
			</Validity>
			<Participant>
				<BIC>AAAADEFF</BIC>
				<NmAndAdr>
					<Nm>A-Bank</Nm>
				</NmAndAdr>
			</Participant>
			<Product>
				<ProductName>SDD b2b</ProductName>
			</Product>
			<CSM>
				<PtyId>
					<BICOrBEI>MARKDEFF</BICOrBEI>
				</PtyId>
				<PreferredIndicator>1</PreferredIndicator>
			</CSM>
			<CutOff>
				<Time>14:00:00</Time>
				<RelDays>0</RelDays>
				<TimeZone>CET</TimeZone>
			</CutOff>
		</RchEntry>
		<RchEntry>
			<Status>existing</Status>
			<Validity>
				<FrDtTm>2013-09-09T15:00:00</FrDtTm>
				<ToDtTm>2018-08-13T15:00:00</ToDtTm>
			</Validity>
			<Participant>
				<BIC>BBBBDEFFXXX</BIC>
				<NmAndAdr>
					<Nm>B-Bank</Nm>
				</NmAndAdr>
			</Participant>
			<Product>
				<ProductName>SDD core</ProductName>
			</Product>
			<CSM>
				<PtyId>
					<PrtryId>
						<Id>Other CSM</Id>
					</PrtryId>
				</PtyId>
				<PreferredIndicator>1</PreferredIndicator>
			</CSM>
			<CutOff>
				<Time>15:00:00</Time>
				<RelDays>0</RelDays>
				<TimeZone>CET</TimeZone>
			</CutOff>
		</RchEntry>
		<RchEntry>
			<Status>existing</Status>
			<Validity>
				<FrDtTm>2018-08-13T15:00:00</FrDtTm>
			</Validity>
			<Participant>
				<BIC>CCCCDEFFXYZ</BIC>
				<NmAndAdr>
					<Nm>XYZ-Bank</Nm>
				</NmAndAdr>
			</Participant>
			<Product>
				<ProductName>SCT</ProductName>
			</Product>
			<CSM>
				<PtyId>
					<PrtryId>
						<Id>Other CSM</Id>
					</PrtryId>
				</PtyId>
				<PreferredIndicator>1</PreferredIndicator>
			</CSM>
			<CutOff>
				<Time>15:00:00</Time>
				<RelDays>0</RelDays>
				<TimeZone>CET</TimeZone>
			</CutOff>
		</RchEntry>
		<RchEntry>
			<Status>existing</Status>
			<Validity>
				<FrDtTm>2013-08-05T15:00:00</FrDtTm>
				<ToDtTm>2018-08-13T15:00:00</ToDtTm>
			</Validity>
			<Participant>
				<BIC>DDDDDEFF</BIC>
				<NmAndAdr>
					<Nm>D-Bank</Nm>
				</NmAndAdr>
			</Participant>
			<Product>
				<ProductName>SDD core</ProductName>
			</Product>
			<CSM>
				<PtyId>
					<BICOrBEI>MARKDEFF</BICOrBEI>
				</PtyId>
				<PreferredIndicator>1</PreferredIndicator>
			</CSM>
			<CutOff>
				<Time>15:00:00</Time>
				<RelDays>0</RelDays>
				<TimeZone>CET</TimeZone>
			</CutOff>
		</RchEntry>
		<RchEntry>
			<Status>existing</Status>
			<Validity>
				<FrDtTm>2018-08-13T15:00:00</FrDtTm>
			</Validity>
			<Participant>
				<BIC>GGGGDEFFXXX</BIC>
				<NmAndAdr>
					<Nm>G-Bank</Nm>
				</NmAndAdr>
			</Participant>
			<Product>
				<ProductName>SDD core</ProductName>
			</Product>
			<CSM>
				<PtyId>
					<BICOrBEI>MARKDEFF</BICOrBEI>
				</PtyId>
				<PreferredIndicator>1</PreferredIndicator>
			</CSM>
			<CutOff>
				<Time>15:00:00</Time>
				<RelDays>0</RelDays>
				<TimeZone>CET</TimeZone>
			</CutOff>
		</RchEntry>
		<RchEntry>
			<Status>existing</Status>
			<Validity>
				<FrDtTm>2018-08-13T15:00:00</FrDtTm>
			</Validity>
			<Participant>
				<BIC>HHHHDEFF</BIC>
				<NmAndAdr>
					<Nm>H-Bank</Nm>
				</NmAndAdr>
			</Participant>
			<Product>
				<ProductName>SCT</ProductName>
			</Product>
			<CSM>
				<PtyId>
					<BICOrBEI>MARKDEFF</BICOrBEI>
				</PtyId>
				<PreferredIndicator>1</PreferredIndicator>
			</CSM>
			<CutOff>
				<Time>15:00:00</Time>
				<RelDays>0</RelDays>
				<TimeZone>CET</TimeZone>
			</CutOff>
		</RchEntry>
		<RchEntry>
			<Status>existing</Status>
			<Validity>
				<FrDtTm>2018-08-13T15:00:00</FrDtTm>
			</Validity>
			<Participant>
				<BIC>JJJJDEFFABC</BIC>
				<NmAndAdr>
					<Nm>J-Bank</Nm>
				</NmAndAdr>
			</Participant>
			<Product>
				<ProductName>SCT</ProductName>
			</Product>
			<CSM>
				<PtyId>
					<BICOrBEI>MARKDEFF</BICOrBEI>
				</PtyId>
				<PreferredIndicator>1</PreferredIndicator>
			</CSM>
			<CutOff>
				<Time>15:00:00</Time>
				<RelDays>0</RelDays>
				<TimeZone>CET</TimeZone>
			</CutOff>
		</RchEntry>
		<RchEntry>
			<Status>existing</Status>
			<Validity>
				<FrDtTm>2018-08-13T15:00:00</FrDtTm>
			</Validity>
			<Participant>
				<BIC>JJJJDEFF</BIC>
				<NmAndAdr>
					<Nm>J-Bank</Nm>
				</NmAndAdr>
			</Participant>
			<Product>
				<ProductName>SCT</ProductName>
			</Product>
			<CSM>
				<PtyId>
					<PrtryId>
						<Id>Other CSM</Id>
					</PrtryId>
				</PtyId>
				<PreferredIndicator>1</PreferredIndicator>
			</CSM>
			<CutOff>
				<Time>15:00:00</Time>
				<RelDays>0</RelDays>
				<TimeZone>CET</TimeZone>
			</CutOff>
		</RchEntry>
		<RchEntry>
			<Status>existing</Status>
			<Validity>
				<FrDtTm>2018-08-13T15:00:00</FrDtTm>
			</Validity>
			<Participant>
				<BIC>KKKKDEFF</BIC>
				<NmAndAdr>
					<Nm>K-Bank</Nm>
				</NmAndAdr>
			</Participant>
			<Product>
				<ProductName>SDD core</ProductName>
			</Product>
			<CSM>
				<PtyId>
					<PrtryId>
						<Id>Other CSM</Id>
					</PrtryId>
				</PtyId>
				<PreferredIndicator>1</PreferredIndicator>
			</CSM>
			<CutOff>
				<Time>15:00:00</Time>
				<RelDays>0</RelDays>
				<TimeZone>CET</TimeZone>
			</CutOff>
		</RchEntry>
	</rocs.001.001.06>
</Document>

=== toivotuo/tapestry/tapestry/router/fixtures/2018081300001DMARKDEFF.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Achtung: Beispieldatei, keine Produktivdaten! -->
<!--Beispieldatei SCL-Teilnehmer, Delta table -->
<Document xmlns="urn:rocs.001.001.06" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:rocs.001.001.06 Rocs.001.001.06.xsd">
  <rocs.001.001.06>
    <GrpHdr>
      <MsgId>MARKDEFF201808090001</MsgId>
      <CreDtTm>2018-08-09T00:00:00</CreDtTm>
      <PtyId>
        <BICOrBEI>MARKDEFFXXX</BICOrBEI>
      </PtyId>
      <FullTable>0</FullTable>
      <FileValidityDate>2018-08-13T00:00:00</FileValidityDate>
    </GrpHdr>
    <RchEntry>
      <Status>new</Status>
      <Validity>
        <FrDtTm>2018-08-13T15:00:00</FrDtTm>
      </Validity>
      <Participant>
        <BIC>AAAADEFF</BIC>
        <NmAndAdr>
          <Nm>A-Bank</Nm>
        </NmAndAdr>
      </Participant>
      <Product>
        <ProductName>SDD core</ProductName>
      </Product>
      <CSM>
        <PtyId>
          <BICOrBEI>MARKDEFF</BICOrBEI>
        </PtyId>
        <PreferredIndicator>1</PreferredIndicator>
      </CSM>
      <CutOff>
        <Time>15:00:00</Time>
        <RelDays>0</RelDays>
        <TimeZone>CET</TimeZone>
      </CutOff>
    </RchEntry>
    <RchEntry>
      <Status>changed</Status>
      <Validity>
        <FrDtTm>2018-08-13T15:00:00</FrDtTm>
      </Validity>
      <Participant>
        <BIC>CCCCDEFFXYZ</BIC>
        <NmAndAdr>
          <Nm>XYZ-Bank</Nm>
        </NmAndAdr>
      </Participant>
      <Product>
        <ProductName>SCT</ProductName>
      </Product>
      <CSM>
        <PtyId>
          <BICOrBEI>MARKDEFF</BICOrBEI>
        </PtyId>
        <PreferredIndicator>1</PreferredIndicator>
      </CSM>
      <CutOff>
        <Time>15:00:00</Time>
        <RelDays>0</RelDays>
        <TimeZone>CET</TimeZone>
      </CutOff>
    </RchEntry>
    <RchEntry>
      <Status>deleted</Status>
      <Validity>
        <FrDtTm>2018-08-13T15:00:00</FrDtTm>
      </Validity>
      <Participant>
        <BIC>DDDDDEFFXXX</BIC>
        <NmAndAdr>
          <Nm>D-Bank</Nm>
        </NmAndAdr>
      </Participant>
      <Product>
        <ProductName>SDD core</ProductName>
      </Product>
      <CSM>
        <PtyId>
          <BICOrBEI>MARKDEFF</BICOrBEI>
        </PtyId>
        <PreferredIndicator>1</PreferredIndicator>
      </CSM>
      <CutOff>
        <Time>15:00:00</Time>
        <RelDays>0</RelDays>
        <TimeZone>CET</TimeZone>
      </CutOff>
    </RchEntry>
    <RchEntry>
      <Status>deleted</Status>
      <Validity>
        <FrDtTm>2018-08-13T14:00:00</FrDtTm>
      </Validity>
      <Participant>
        <BIC>DDDDDEFFXXX</BIC>
        <NmAndAdr>
          <Nm>D-Bank</Nm>
        </NmAndAdr>
      </Participant>
      <Product>
        <ProductName>SDD b2b</ProductName>
      </Product>
      <CSM>
        <PtyId>
          <BICOrBEI>MARKDEFF</BICOrBEI>
        </PtyId>
        <PreferredIndicator>1</PreferredIndicator>
      </CSM>
      <CutOff>
        <Time>14:00:00</Time>
        <RelDays>0</RelDays>
        <TimeZone>CET</TimeZone>
      </CutOff>
    </RchEntry>
    <RchEntry>
      <Status>deleted</Status>
      <Validity>
        <FrDtTm>2018-08-13T15:00:00</FrDtTm>
      </Validity>
      <Participant>
        <BIC>EEEEDEFF</BIC>
        <NmAndAdr>
          <Nm>E-Bank</Nm>
        </NmAndAdr>
      </Participant>
      <Product>
        <ProductName>SCT</ProductName>
      </Product>
      <CSM>
        <PtyId>
          <PrtryId>
            <Id>Other CSM</Id>
          </PrtryId>
        </PtyId>
        <PreferredIndicator>1</PreferredIndicator>
      </CSM>
      <CutOff>
        <Time>15:00:00</Time>
        <RelDays>0</RelDays>
        <TimeZone>CET</TimeZone>
      </CutOff>
    </RchEntry>
  </rocs.001.001.06>
</Document>
